require 'rake'

task :default => [:console]

desc 'Starts the frontend server.'
task :server do
  sh 'bundle exec thin start'
end

desc "Open an irb session preloaded with this app."
task :console do
  #sh "bundle exec irb -r ./app/psio"
  cd 'app' do
    sh 'bundle exec irb -I . -r ./psio'
  end
end