#= require      ./vendor/jquery-1.8.1.min.js
#= require      ./vendor/underscore-min.js
#= require      ./vendor/backbone-min.js
#= require      ./vendor/bootstrap.min.js
#= require_tree ./vendor
#= require_self
#= require      ./router.coffee
#= require      ./init.coffee
window.Psio = {}
